# Generated by Django 5.0.7 on 2024-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
